### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by antwal** [ich777/docker-thunderbird#11]
Docker Log:

```
---Ensuring UID: 1000 matches user---
usermod: no changes
---Ensuring GID: 100 matches user---
---Setting umask to 000---
---Checking for optional scripts---
---No optional script found, continuing---
---Checking configuration for noVNC---
Nothing to do, noVNC resizing set to default
Nothing to do, noVNC qaulity set to default
Nothing to do, noVNC compression set to default
---Taking ownership of data...---
---Starting...---
---Version Check---
---Thunderbird not installed, installing---

/thunderbird/Thunde   0%[                    ]       0  --.-KB/s               
/thunderbird/Thunde   4%[                    ]   3.38M  16.8MB/s               
/thunderbird/Thunde  22%[===>                ]  16.37M  40.9MB/s               
/thunderbird/Thunde  41%[=======>            ]  29.78M  49.6MB/s               
/thunderbird/Thunde  62%[===========>        ]  44.77M  55.7MB/s               
/thunderbird/Thunde  82%[===============>    ]  59.32M  59.1MB/s               
/thunderbird/Thunde 100%[===================>]  71.49M  60.2MB/s    in 1.2s    
---Sucessfully downloaded Thunderbird---
---Preparing Server---
---Resolution check---
---Checking for old logfiles---
---Checking for old display lock files---
---Starting TurboVNC server---
---Starting Fluxbox---
---Starting noVNC server---
WebSocket server settings:
  - Listen on :8080
  - Web server. Web root: /usr/share/novnc
  - No SSL/TLS support (no cert file)
  - Backgrounding (daemon)
---Starting Thunderbird---
[GFX1-]: glxtest: libpci missing
[Parent 89, Main Thread] WARNING: Failed to execute child process “update-desktop-database” (No such file or directory): 'glib warning', file /builds/worker/checkouts/gecko/toolkit/xre/nsSigHandlers.cpp:167

(thunderbird:89): GLib-GIO-WARNING **: 20:36:45.258: Failed to execute child process “update-desktop-database” (No such file or directory)
```

noVNC Login:

<img width="750" alt="Schermata 2022-08-16 alle 20 32 15" src="https://user-images.githubusercontent.com/410736/184953442-a6d1da85-ece5-4329-b278-ccc25d4ad846.png">

**Comment by ich777** [comment]
Please clear the browser cache.

**Comment by antwal** [comment]
already tried, I totally deleted the container also but always the same error

**Comment by ich777** [comment]
This is definitely a issue with the browser, have you already tried a different browser or a private window?

The log is looking good to me, the error on the end can be ignored, I don't cut everything in the logs... :)

Please try to create another port mapping with 5900:5900 and try a native VNC client like TightVNC and connect to port 5900

**Comment by ich777** [comment]
To what IP and Port are you trying to connect?

**Comment by ich777** [comment]
Can you post your full `docker run` command? On what OS do you run the container?

**Comment by antwal** [comment]
> This is definitely a issue with the browser, have you already tried a different browser or a private window?

tested chrome, safari, opera, brave, edge all the same problem, if I open the address without "vnc.html ..." I see this

<img width="709" alt="Schermata 2022-08-16 alle 21 22 08" src="https://user-images.githubusercontent.com/410736/184964420-3a936c17-e70d-44dd-9337-88127c2e279f.png">


> 
> The log is looking good to me, the error on the end can be ignored, I don't cut everything in the logs... :)
> 

ok

> Please try to create another port mapping with 5900:5900 and try a native VNC client like TightVNC and connect to port 5900


<img width="1026" alt="Schermata 2022-08-16 alle 21 21 21" src="https://user-images.githubusercontent.com/410736/184964322-830a320e-ad53-441b-8518-204c984f06d5.png">

> To what IP and Port are you trying to connect?

see screenshot above

> Can you post your full docker run command? On what OS do you run the container?

<img width="1717" alt="Schermata 2022-08-16 alle 21 16 25" src="https://user-images.githubusercontent.com/410736/184964755-e4609c9a-ef90-41e0-bab6-8ce3f56c300d.png">

Debian 5.10.70-1~bpo10+1 (2021-10-10) x86_64 GNU/Linux

**Comment by ich777** [comment]
> tested chrome, safari, opera, brave, edge all the same problem, if I open the address without "vnc.html ..." I see this

This is looking also good to me.


> see screenshot above

So it seems to be working fine via a native VNC client but not over noVNC.


I've now set up a new instance on my server and it is all working flawelssly:

![grafik](https://user-images.githubusercontent.com/28066518/184965979-bc0d5aa3-34b7-44c2-9ae9-b3c92cf3a407.png)

I'm assuming you have mapped the port like so: `3000:8080`?

Just for refference I've post my `docker run` command here too:
`docker run -d --name='ThunderbirdTest' --net='bridge' -e TZ="Europe/Berlin" -e HOST_OS="Unraid" -e HOST_HOSTNAME="chipsServer" -e HOST_CONTAINERNAME="ThunderbirdTest" -e 'THUNDERBIRD_V'='latest' -e 'THUNDERBIRD_LANG'='it' -e 'CUSTOM_RES_W'='1280' -e 'CUSTOM_RES_H'='768' -e 'EXTRA_PARAMETERS'='' -e 'UID'='99' -e 'GID'='100' -e 'UMASK'='000' -l net.unraid.docker.managed=dockerman -l net.unraid.docker.webui='http://[IP]:[PORT:8080]/vnc.html?autoconnect=true' -l net.unraid.docker.icon='https://raw.githubusercontent.com/ich777/docker-templates/master/ich777/images/thunderbird.png' -p '9085:8080/tcp' -v '/mnt/cache/appdata/testthunderbird/':'/thunderbird':'rw' --restart=unless-stopped --shm-size=2G 'ich777/thunderbird'`


> Debian 5.10.70-1~bpo10+1 (2021-10-10) x86_64 GNU/Linux

I have to fire up my Debian machine tomorrow and try it there too but AFAIK it should work there fine too.


I'm using this container on a daily basis and it needs to run because it has all my mail accounts in it and it is basically my main mail app.

**Comment by antwal** [comment]
i used the standard configuration and it works, on port 8080

is it possible to update noVNC to the latest version?

Thanks.

**Comment by ich777** [comment]
> i used the standard configuration and it works, on port 8080

But it should also work if you map it to another port like I did in my example...


> is it possible to update noVNC to the latest version?

This was planed to be done when the new version from TurboVNC drops since I have many noVNC containers and I usually test everything if they are running fine and I want to avoid testing twice.
Is it in your case necessary to be on the latest version?

**Comment by antwal** [comment]
it seems to me there is a slight graphic lag

i am testing the latest version of novnc with tigervnc on debian 11 and currently have no problems

**Comment by ich777** [comment]
I don't see any lag on my machine...

I will test this out tomorrow but from what I know the difference in performance from noVNC 1.2.0 to 1.3.0 shouldn't be noticeable because there where no fixes in terms of performance: [Click](https://github.com/novnc/noVNC/releases/tag/v1.3.0)

**Comment by antwal** [comment]
ok

**Comment by ich777** [comment]
I will look into this and try it tomorrow if there is any latency or visual improvements over noVNC 1.2.0

**Comment by ich777** [comment]
@antwal just to let you know, I‘ve tested the performance difference between noVNC 1.2.0 and 1.3.0 and there is no real difference in terms of performance.
