### ISSUE TITLE
Support for older versions (also x86)

### ISSUE THREAD

**Issue by le-patenteux** [ich777/docker-thunderbird#7]
Hello ich777, thank you for this nice docker image!

Is it possible to support older versions of thunderbird? Like x86 32 bit versions.
Also, versions older than 1.0 that have a different folder structure and can't be downloaded with that setup.

This might look like a strange request, but it would be a nice way to revisit the history of this software! Thanks a lot!

**Comment by ich777** [comment]
@Normand-Nadon **re x86 version:** In the current dtate it‘s not possible since it‘s designed to only pull the x86_64 version and also the libraries are missing which are required to run the x86 version.

**re older versions:** This would be also possible but I‘m really not sure if it‘s possible in terms of the shared libraries because maybe the old versions from Thunderbird are not dfully compatible with the versions from the libraries from Debian Bullseye.
The different file structure complicates this a bit more and TBH I‘m not really familiar with the older file structures…

Also don‘t forget that this container works a little different since the Thunderbird binaries are not included in the container rather they are pulled at the first start and the container checks on each start/restart if there is a newer version from Thunderbird availabel, if `latest` is used.

You can of course fork the container and modify it to be compatible with x86 and/or older versions from Thunderbird but I would recommend that you do this/create another branch like `x86` so that the `master` branch isn‘t affected by this change.

The main reason that I can‘t look into this is because I‘m currently real busy in real life and only try to keep all of my Containers and my Plugins for Unraid running.

Please keep me updated if this is a option for you.
I‘m also happy to accept PRs and build the container afterwards.

**Comment by le-patenteux** [comment]
Thanks for taking the time! I don't think I can modify the container myself... but I will try! Nice pet project to run on the side!
I will keep you posted if something ends-up working...

Have a nice day

**Comment by ich777** [comment]
Sorry for the late answer @Normand-Nadon, but as said, really busy at the moment.
Okay, can this issue then be closed now or should we left it open?

**Comment by le-patenteux** [comment]
I can't do this myself, and I don't want to let this issue linger in your project! have a nice day!
